uploads = []
generated = []

[[outputs]]
id = "qJB8x5bipUMYjEIKltYqL"
uri = "file://exports/顽童日记_PRD.docx"
type = "word_document"
title = "顽童日记 PRD v1.0 （Word 文档）"

[[outputs]]
id = "fzdUmx-kZoDYVxHgpIiMF"
uri = "file://exports/顽童日记_产品规划.docx"
type = "word_document"
title = "顽童日记 产品规划 2026 Roadmap"
