import { Router, type IRouter } from "express";
import healthRouter from "./health";
import entriesRouter from "./entries";
import photosRouter from "./photos";
import tagsRouter from "./tags";
import statsRouter from "./stats";
import storageRouter from "./storage";
import aiRouter from "./ai";
import socialRouter from "./social";
import geocodeRouter from "./geocode";
import weatherRouter from "./weather";
import digestRouter from "./digest";
import planRouter from "./plan";
import notificationsRouter from "./notifications";
import collectionsRouter from "./collections";
import collaboratorsRouter from "./collaborators";
import payHupiRouter from "./pay-hupi";
import prefsRouter from "./prefs";
import feedbackRouter from "./feedback";
import safetyRouter from "./safety";
import downloadsRouter from "./downloads";
import proxyRouter from "./proxy";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/entries", entriesRouter);
router.use("/entries", collaboratorsRouter);
router.use("/photos", photosRouter);
router.use("/tags", tagsRouter);
router.use("/stats", statsRouter);
router.use(storageRouter);
router.use("/ai", aiRouter);
router.use(socialRouter);
router.use(geocodeRouter);
router.use(weatherRouter);
router.use(digestRouter);
router.use(planRouter);
router.use(notificationsRouter);
router.use("/collections", collectionsRouter);
router.use("/pay/hupi", payHupiRouter);
router.use(prefsRouter);
router.use(feedbackRouter);
router.use(safetyRouter);
router.use(downloadsRouter);
router.use(proxyRouter);

export default router;
