// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/entries-redesign/DesktopView.tsx": () => import("../components/mockups/entries-redesign/DesktopView.tsx"),
  "./components/mockups/entries-redesign/MobileView.tsx": () => import("../components/mockups/entries-redesign/MobileView.tsx"),
  "./components/mockups/me-page/MePage.tsx": () => import("../components/mockups/me-page/MePage.tsx"),
  "./components/mockups/home-redesign/DesktopView.tsx": () => import("../components/mockups/home-redesign/DesktopView.tsx"),
  "./components/mockups/home-redesign/HomePage.tsx": () => import("../components/mockups/home-redesign/HomePage.tsx"),
  "./components/mockups/home-redesign/MobileView.tsx": () => import("../components/mockups/home-redesign/MobileView.tsx")
};
